import type { Category, EmailDifference } from './types';

export const categories: Category[] = [
  {
    id: 'instant-messaging',
    title: 'Instant Messaging',
    icon: 'MessageSquare',
    color: 'hsl(239, 84%, 67%)',
    description: 'Real-time text conversations over the internet.',
    apps: [
      {
        id: 'whatsapp',
        name: 'WhatsApp',
        icon: 'MessageCircle',
        color: '#25D366',
        description: 'The most popular messaging app, with a focus on E2E encryption.',
        protocols: ['Signal Protocol', 'XMPP (modified)', 'Noise Protocol Framework', 'WebRTC'],
        backend: [
          { name: 'Erlang/OTP', type: 'language' },
          { name: 'FreeBSD', type: 'platform' },
          { name: 'Mnesia', type: 'database' },
        ],
        frontend: [
            { name: 'React Native', type: 'framework' },
            { name: 'Electron', type: 'framework' },
        ],
        useCase: 'Personal/family communication, 2B+ users, end-to-end encrypted by default.',
        coreConcepts: ['Persistent TCP connections', 'Push notifications via FCM/APNs', 'Media stored temporarily with keys on devices'],
        keyTech: ['Double Ratchet Algorithm', 'Curve25519', 'X3DH key agreement'],
        technicalExplanation: "WhatsApp routes messages using a modified version of the XMPP protocol, running on highly-concurrent Erlang/OTP backend services. It ensures message privacy through the Signal Protocol, which provides end-to-end encryption. This means only the sender and receiver can read the messages. The system relies on persistent TCP connections for instant message delivery and uses Apple's and Google's push notification services as a fallback.",
        dataFlow: [
          { step: 'Encryption', detail: 'Message is E2E encrypted on sender\'s device using Signal Protocol.' },
          { step: 'Connection', detail: 'App sends the encrypted message over a persistent TCP connection to a WhatsApp server.' },
          { step: 'Routing', detail: 'The server, running on Erlang, routes the message to the recipient without being able to read it.' },
          { step: 'Delivery', detail: 'Recipient\'s device receives the message. If offline, APNs/FCM push notification is triggered on reconnect.' },
          { step: 'Decryption', detail: 'Recipient\'s app uses its private key to decrypt and display the message.' },
        ],
      },
      {
        id: 'telegram',
        name: 'Telegram',
        icon: 'Send',
        color: '#0088cc',
        description: 'Cloud-based messaging with a focus on speed and features.',
        protocols: ['MTProto 2.0', 'TCP/UDP Hybrid', 'WebRTC'],
        backend: [
          { name: 'C++', type: 'language' },
          { name: 'Custom Distributed System', type: 'infrastructure' },
        ],
        frontend: [
            { name: 'Swift/Kotlin', type: 'language' },
            { name: 'React', type: 'framework' },
        ],
        useCase: 'Large group chats (200K members), channels, bot ecosystem, cloud-based messaging.',
        coreConcepts: ['Client-server encryption (default)', 'E2E encryption for "Secret Chats"', 'Distributed system for speed'],
        keyTech: ['MTProto 2.0', 'AES-256 Encryption', 'Custom server infrastructure'],
        technicalExplanation: "Telegram uses its custom-built protocol, MTProto 2.0, for communication between clients and its distributed server network. By default, chats are client-server encrypted and stored in the cloud, allowing seamless multi-device sync. For maximum privacy, users can opt into 'Secret Chats,' which enable end-to-end encryption and are not stored on Telegram's servers.",
        dataFlow: [
          { step: 'Connection', detail: 'Client establishes a connection with a data center using the MTProto protocol.' },
          { step: 'Encryption (Cloud Chat)', detail: 'Message is client-server encrypted and sent to Telegram\'s cloud.' },
          { step: 'Storage & Sync', detail: 'Server stores the message, allowing it to be accessed from any logged-in device.' },
          { step: 'Delivery', detail: 'The message is pushed to all of the recipient\'s active devices.' },
        ],
      },
      {
        id: 'signal',
        name: 'Signal',
        icon: 'Lock',
        color: '#3a76f0',
        description: 'The gold standard for private and secure communication.',
        protocols: ['Signal Protocol', 'X3DH', 'Double Ratchet', 'WebRTC'],
        backend: [
          { name: 'Java', type: 'language' },
          { name: 'AWS', type: 'infrastructure' },
          { name: 'PostgreSQL', type: 'database' },
          { name: 'Redis', type: 'database' },
        ],
        frontend: [
            { name: 'Electron', type: 'framework' },
            { name: 'Swift/Kotlin', type: 'language' },
        ],
        useCase: 'Privacy-focused users, journalists, activists - maximum security.',
        coreConcepts: ['E2E encryption for everything', 'Minimal metadata collection', 'Open-source clients and server'],
        keyTech: ['X3DH key agreement', 'Double Ratchet', 'Sealed Sender (hides metadata)'],
        technicalExplanation: 'Signal is designed for maximum privacy, applying the Signal Protocol for end-to-end encryption to all communications by default. Its server infrastructure, running on AWS, is engineered to store the minimum possible user metadata. The "Sealed Sender" feature even encrypts sender information, making it difficult for anyone, including Signal, to know who is messaging whom.',
        dataFlow: [
          { step: 'Key Agreement', detail: 'X3DH protocol establishes a shared secret key between users.' },
          { step: 'Encryption', detail: 'Every message is E2E encrypted using the Double Ratchet algorithm for forward secrecy.' },
          { step: 'Routing', detail: 'The encrypted payload is sent to Signal servers, which route it to the recipient.' },
          { step: 'Metadata Obfuscation', detail: 'Sealed Sender technology hides who the message is from.' },
          { step: 'Decryption', detail: 'Only the intended recipient can decrypt the message.' },
        ],
      },
    ],
  },
  {
    id: 'voip',
    title: 'VoIP (Voice over IP)',
    icon: 'Phone',
    color: 'hsl(163, 82%, 42%)',
    description: 'Transmitting voice and video calls over the internet.',
    apps: [
      {
        id: 'discord',
        name: 'Discord',
        icon: 'Mic',
        color: '#5865F2',
        description: 'Voice, video, and text for communities, especially gamers.',
        protocols: ['WebRTC', 'WebSocket', 'Opus (audio)', 'VP8/VP9 (video)'],
        backend: [
          { name: 'Elixir/Erlang', type: 'language' },
          { name: 'Rust', type: 'language' },
          { name: 'Go', type: 'language' },
          { name: 'ScyllaDB', type: 'database' },
        ],
        frontend: [
            { name: 'React', type: 'framework' },
            { name: 'React Native', type: 'framework' },
            { name: 'Electron', type: 'framework' },
        ],
        useCase: 'Gaming communities, voice channels, streaming, persistent servers.',
        coreConcepts: ['Voice channels use UDP for low latency', 'Automatic server routing for best performance', 'Guild/channel structure'],
        keyTech: ['Custom voice infrastructure', 'RTP (Real-time Transport Protocol)', 'Opus codec'],
        technicalExplanation: 'Discord leverages WebRTC for low-latency voice and video, routing audio through dedicated voice servers written in Rust for high performance. Text chat and real-time events are handled by a separate gateway system built with Elixir, using WebSockets for communication. This hybrid architecture optimizes for both high-quality voice and scalable real-time messaging.',
        dataFlow: [
          { step: 'Signaling', detail: 'Client signals intent to join a voice channel via WebSocket to the Gateway.' },
          { step: 'Connection', detail: 'Gateway provides details for the client to connect to a dedicated voice server over WebRTC (UDP).'},
          { step: 'Media Stream', detail: 'Client sends Opus-encoded audio packets to the voice server using SRTP.' },
          { step: 'Mixing', detail: 'The server mixes audio from all participants and sends a single stream back to each client.' },
        ],
      },
      {
        id: 'skype',
        name: 'Skype',
        icon: 'Video',
        color: '#00aff0',
        description: 'One of the pioneers of consumer VoIP and video calling.',
        protocols: ['WebRTC', 'SILK (audio)', 'VP9 (video)', 'STUN/TURN'],
        backend: [
          { name: 'C++', type: 'language' },
          { name: 'Microsoft Azure', type: 'infrastructure' },
        ],
        frontend: [
            { name: 'Electron', type: 'framework' },
            { name: 'React Native', type: 'framework' },
        ],
        useCase: 'Video calls, international voice calls, business meetings.',
        coreConcepts: ['Transition from P2P to cloud-based architecture', 'NAT traversal using STUN/TURN', 'Adaptive bitrate streaming'],
        keyTech: ['SILK audio codec', 'Echo cancellation', 'Noise suppression algorithms'],
        technicalExplanation: 'Originally famous for its peer-to-peer (P2P) architecture, modern Skype now primarily uses a cloud-based model running on Microsoft Azure. It uses WebRTC standards for browser clients and its proprietary protocols for native apps. For NAT traversal, it employs STUN to discover public IP addresses and TURN to relay media when a direct connection is not possible.',
        dataFlow: [
          { step: 'Signaling', detail: 'Call setup and signaling is handled by centralized servers on Azure.' },
          { step: 'Connectivity Check', detail: 'ICE framework uses STUN/TURN to establish the best media path (P2P or relayed).' },
          { step: 'Media Relay', detail: 'Media (audio/video) is streamed to Azure servers, which then forward it to other participants.'},
          { step: 'Codec', detail: 'Voice is encoded with the SILK codec, and video with VP9, for quality and efficiency.' },
        ],
      },
    ],
  },
  {
    id: 'forums-discussion',
    title: 'Forums & Discussion',
    icon: 'MessagesSquare',
    color: 'hsl(39, 96%, 51%)',
    description: 'Asynchronous, threaded conversations for communities.',
    apps: [
      {
        id: 'reddit',
        name: 'Reddit',
        icon: 'MessageSquareText',
        color: '#FF4500',
        description: 'A network of communities based on people\'s interests.',
        protocols: ['HTTP/HTTPS', 'REST API', 'GraphQL', 'WebSocket'],
        backend: [
          { name: 'Python', type: 'language' },
          { name: 'Go', type: 'language' },
          { name: 'PostgreSQL', type: 'database' },
          { name: 'Cassandra', type: 'database' },
          { name: 'Redis', type: 'database' },
        ],
        frontend: [{ name: 'React', type: 'framework' }],
        useCase: 'Community discussions, content aggregation, voting system, subreddit moderation.',
        coreConcepts: ['Asynchronous threaded discussions', 'Karma/voting system', 'Distributed caching for performance'],
        keyTech: ['Vote ranking algorithms (Hot, Best)', 'Anti-spam systems', 'CDN for media delivery'],
        technicalExplanation: 'Reddit operates on a microservices architecture, with newer services written in Go and legacy systems in Python. It uses PostgreSQL for structured data like users and subreddits, and Cassandra for massive-scale data like comments and votes. A complex ranking algorithm determines which posts are shown, and Redis is used extensively for caching everything from post scores to user sessions to reduce database load.',
        dataFlow: [
          { step: 'Post Submission', detail: 'User submits a post via HTTP request to Reddit\'s backend.'},
          { step: 'Processing', detail: 'The post is stored in PostgreSQL and enters a moderation/spam filter queue.' },
          { step: 'Indexing', detail: 'Post content is indexed for search. Votes and comments are stored in Cassandra.'},
          { step: 'Cache', detail: 'Hot posts and user feeds are pre-calculated and cached in Redis for fast retrieval.'},
          { step: 'Display', detail: 'When another user browses, they are served the cached, ranked content.' },
        ],
      },
      {
        id: 'stack-overflow',
        name: 'Stack Overflow',
        icon: 'Code',
        color: '#F48024',
        description: 'The largest online community for programmers to learn and share knowledge.',
        protocols: ['HTTP/HTTPS', 'WebSocket'],
        backend: [
          { name: 'C#/.NET', type: 'language' },
          { name: 'MS SQL Server', type: 'database' },
          { name: 'Redis', type: 'database' },
          { name: 'Elasticsearch', type: 'database' },
        ],
        frontend: [{ name: 'Razor Pages', type: 'framework' }],
        useCase: 'Technical Q&A, reputation system, knowledge base for developers.',
        coreConcepts: ['Reputation-based moderation', 'Structured Q&A format', 'Tag-based organization'],
        keyTech: ['Full-text search with Elasticsearch', 'Aggressive caching strategies', 'WebSockets for real-time notifications'],
        technicalExplanation: 'Stack Overflow is built on the .NET framework, prioritizing server-side rendering and performance. Core data is stored in SQL Server, but a critical component is Elasticsearch, which powers its fast, sophisticated search. Redis is used for caching and managing distributed tasks. The architecture is a monolith with a strong emphasis on efficiency and speed, famously running on a small number of powerful bare-metal servers.',
        dataFlow: [
          { step: 'Question Posted', detail: 'A user posts a question, which is saved to the SQL Server database.' },
          { step: 'Indexing', detail: 'The question and its content are immediately indexed by Elasticsearch.' },
          { step: 'Real-time Update', detail: 'WebSockets push notifications to users following relevant tags.' },
          { step: 'Search', detail: 'Another user searches for a similar problem, querying the Elasticsearch index.' },
          { step: 'Answer Retrieval', detail: 'The system retrieves the relevant question and its answers from SQL Server for display.' },
        ],
      },
    ],
  },
  {
    id: 'video-chat',
    title: 'Video Chat Platforms',
    icon: 'Video',
    color: 'hsl(326, 83%, 61%)',
    description: 'Face-to-face communication for meetings and social calls.',
    apps: [
      {
        id: 'zoom',
        name: 'Zoom',
        icon: 'Group',
        color: '#2D8CFF',
        description: 'The market leader in video conferencing for business and personal use.',
        protocols: ['WebRTC (browser)', 'Custom UDP protocol (app)', 'H.264/H.265'],
        backend: [
          { name: 'C++', type: 'language' },
          { name: 'Go', type: 'language' },
          { name: 'Distributed Architecture', type: 'infrastructure' },
          { name: 'AWS/Oracle Cloud', type: 'infrastructure' },
        ],
        frontend: [
          { name: 'C++ (Native)', type: 'language' },
          { name: 'React', type: 'framework' },
        ],
        useCase: 'Business meetings, webinars, screen sharing, large group calls.',
        coreConcepts: ['Server-side mixing (MCU/SFU)', 'Screen sharing optimization', 'Gallery view rendering'],
        keyTech: ['Custom video routing', 'Bandwidth adaptation', 'Breakout Rooms'],
        technicalExplanation: 'Zoom uses a sophisticated distributed architecture of multimedia routers (MMRs) to handle video streams. Unlike pure P2P, clients send their video to a server, which then distributes it to others. This can be a Selective Forwarding Unit (SFU) that forwards streams selectively, or a Multipoint Control Unit (MCU) that mixes streams into one. This server-centric model provides better quality and stability for large meetings.',
        dataFlow: [
          { step: 'Signaling', detail: 'Client connects to a Zoom server to join a meeting and handle metadata.' },
          { step: 'Media Upload', detail: 'Client encodes video (H.264) and audio, then sends it via a custom UDP protocol to the nearest Zoom data center.' },
          { step: 'Server Processing', detail: 'Zoom\'s SFU/MCU receives the stream and prepares it for distribution to other participants.' },
          { step: 'Media Download', detail: 'The server sends the relevant video/audio streams to each participant.' },
          { step: 'Decoding & Rendering', detail: 'Client app decodes the streams and renders them in the gallery or speaker view.' },
        ],
      },
       {
        id: 'google-meet',
        name: 'Google Meet',
        icon: 'VideoIcon',
        color: '#00A86B',
        description: 'Google\'s secure and easy-to-use video conferencing solution.',
        protocols: ['WebRTC', 'QUIC', 'VP9', 'SRTP'],
        backend: [
          { name: 'Go', type: 'language' },
          { name: 'C++', type: 'language' },
          { name: 'Google Global Network', type: 'infrastructure' },
          { name: 'Spanner', type: 'database' },
        ],
        frontend: [
            { name: 'JavaScript', type: 'language' },
            { name: 'Native Apps', type: 'platform' },
        ],
        useCase: 'Integrated with Google Workspace, business/education, browser-first.',
        coreConcepts: ['Browser-first design', 'AI-powered noise cancellation', 'Live captions via speech-to-text'],
        keyTech: ['Google\'s global network for low latency', 'QUIC protocol', 'VP9 video codec'],
        technicalExplanation: 'Google Meet is built on WebRTC and heavily leverages Google\'s private global network to reduce latency and improve call quality. It uses a browser-first approach, minimizing the need for plugins. A key feature is its use of the QUIC protocol, which reduces connection setup time and improves performance on poor networks compared to traditional TCP.',
        dataFlow: [
          { step: 'Authentication', detail: 'User joins via Google Account, leveraging Google\'s identity services.'},
          { step: 'Signaling', detail: 'WebRTC signaling establishes connection parameters through Google\'s servers.' },
          { step: 'Media Path', detail: 'Client media is sent over SRTP (often tunneled through QUIC) to the nearest Google edge node.' },
          { step: 'Cloud SFU', detail: 'Google\'s Selective Forwarding Unit (SFU) routes video streams efficiently between participants.' },
          { step: 'AI Enhancement', detail: 'On-device or in-cloud AI models process audio for noise cancellation and generate live captions.' },
        ],
      },
    ],
  },
  {
    id: 'collaborative-tools',
    title: 'Collaborative Tools',
    icon: 'Briefcase',
    color: 'hsl(268, 93%, 66%)',
    description: 'Tools that combine messaging, file sharing, and integrations.',
    apps: [
      {
        id: 'slack',
        name: 'Slack',
        icon: 'Slack',
        color: '#4A154B',
        description: 'A channel-based messaging platform for workplace communication.',
        protocols: ['WebSocket', 'HTTP/HTTPS', 'RTM API'],
        backend: [
          { name: 'Java', type: 'language' },
          { name: 'PHP (legacy)', type: 'language' },
          { name: 'MySQL', type: 'database' },
          { name: 'Redis', type: 'database' },
          { name: 'Apache Kafka', type: 'infrastructure' },
        ],
        frontend: [
            { name: 'React', type: 'framework' },
            { name: 'Electron', type: 'framework' },
        ],
        useCase: 'Workplace communication, integrations with 2000+ tools, organized by channels.',
        coreConcepts: ['Workspace-based organization', 'Threaded conversations', 'Rich third-party integrations'],
        keyTech: ['Event-driven architecture with Kafka', 'Flannel Service Mesh', 'Vitess for MySQL scaling'],
        technicalExplanation: 'Slack\'s real-time functionality is powered by WebSockets, keeping a persistent connection to the client for instant message delivery. The backend is an event-driven microservices architecture, using Kafka to manage the flow of messages and events between services. Data is primarily stored in sharded MySQL databases, scaled using Vitess, with extensive caching in Redis.',
        dataFlow: [
          { step: 'Message Post', detail: 'Client sends a message via WebSocket to Slack\'s real-time gateway.' },
          { step: 'Event Bus', detail: 'The gateway publishes a "message posted" event to a Kafka topic.' },
          { step: 'Processing', detail: 'Various microservices (e.g., search indexer, notification service) consume this event.' },
          { step: 'Storage', detail: 'The message service writes the message to the appropriate MySQL shard.' },
          { step: 'Fan-out', detail: 'The gateway pushes the message out via WebSocket to all other subscribed clients in the channel.' },
        ],
      },
      {
        id: 'microsoft-teams',
        name: 'Microsoft Teams',
        icon: 'Users',
        color: '#6264A7',
        description: 'The hub for teamwork in Microsoft 365, integrating chat, meetings, and files.',
        protocols: ['WebRTC', 'SignalR', 'HTTP/HTTPS'],
        backend: [
          { name: '.NET/C#', type: 'language' },
          { name: 'Azure Communication Services', type: 'platform' },
          { name: 'SharePoint/OneDrive', type: 'database' },
        ],
        frontend: [
            { name: 'React', type: 'framework' },
            { name: 'Electron', type: 'framework' },
            { name: 'Angular (legacy)', type: 'framework' },
        ],
        useCase: 'Enterprise communication, tight integration with Office 365.',
        coreConcepts: ['Deep Microsoft ecosystem integration', 'Channels tied to Teams/projects', 'Unified files, chat, and meetings'],
        keyTech: ['Azure Active Directory for auth', 'SharePoint for file storage', 'Microsoft Graph API'],
        technicalExplanation: 'Microsoft Teams is deeply integrated into the Azure and Microsoft 365 ecosystem. Real-time messaging is handled by Azure SignalR, while voice and video are built on Azure Communication Services (which uses WebRTC). A key architectural feature is its use of SharePoint and OneDrive for Business for all file storage, meaning files in a Teams channel are actually stored in a SharePoint site collection.',
        dataFlow: [
          { step: 'Authentication', detail: 'User authenticates via Azure Active Directory (AAD).' },
          { step: 'File Upload', detail: 'User uploads a file. The client API uploads it to the SharePoint site associated with the Team.' },
          { step: 'Message Post', detail: 'User sends a message mentioning the file. The message is sent to the Teams backend service.' },
          { step: 'Notification', detail: 'Azure SignalR pushes the new message to all channel members.' },
          { step: 'File Access', detail: 'Other users click the file link, which directs them to SharePoint with their AAD credentials.' },
        ],
      },
    ],
  },
];

export const emailComparison: EmailDifference = {
    id: 'email-comparison',
    title: 'How is Email Different?',
    description: 'Email is the grandparent of digital communication. It\'s built on a different philosophy: asynchronous and decentralized.',
    icon: 'Mail',
    color: '#f59e0b',
    keyDifferences: [
        {
            title: 'Communication Model',
            comparison: [
                { name: 'Real-time Apps', details: 'Designed for synchronous, conversational "chat." Both parties are often online together. Presence indicators (online, typing) are common.' },
                { name: 'Email', details: 'Asynchronous "store-and-forward" model. A server stores the message until the recipient\'s server is ready. No expectation of an instant reply.' },
            ]
        },
        {
            title: 'Protocols',
            comparison: [
                { name: 'Real-time Apps', details: 'Use protocols like WebSockets, WebRTC, and proprietary UDP-based systems optimized for low latency and persistent connections.' },
                { name: 'Email', details: 'Relies on a set of federated protocols: SMTP (Simple Mail Transfer Protocol) for sending, and POP3/IMAP for receiving. Anyone can run a mail server.' },
            ]
        },
        {
            title: 'Centralization',
            comparison: [
                { name: 'Real-time Apps', details: 'Typically centralized. All users are on the same proprietary system (e.g., you can\'t send a WhatsApp message to a Telegram user).' },
                { name: 'Email', details: 'Federated and decentralized. A Gmail user can send a message to an Outlook user because they both "speak" the same open protocols (SMTP, IMAP).' },
            ]
        },
        {
            title: 'Data Structure',
            comparison: [
                { name: 'Real-time Apps', details: 'Messages are often small data packets, part of a continuous stream or session.' },
                { name: 'Email', details: 'Each email is a self-contained document, with structured headers (To, From, Subject) and a body, defined by RFC 5322.' },
            ]
        }
    ]
};
