'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogTrigger
} from '@/components/ui/dialog';
import { Wand2, Loader2, AlertTriangle } from 'lucide-react';
import { explainBrowserDetails } from '@/ai/flows/explain-browser-details';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { ScrollArea } from '@/components/ui/scroll-area';

export function AIExplainer({
  contentToExplain,
  title,
}: {
  contentToExplain: string;
  title: string;
}) {
  const [isOpen, setIsOpen] = useState(false);
  const [explanation, setExplanation] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleExplain = async () => {
    if (explanation) return; // Don't re-fetch if we already have it
    setIsLoading(true);
    setError('');
    try {
      const result = await explainBrowserDetails({ content: contentToExplain });
      setExplanation(result.explanation);
    } catch (e) {
      setError('An error occurred while fetching the explanation. Please try again later.');
      console.error(e);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          onClick={handleExplain}
          className="gap-2 text-accent-foreground/90 hover:text-accent-foreground bg-accent/20 hover:bg-accent/30 border-accent/30"
        >
          <Wand2 className="h-4 w-4" />
          Explain with AI
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle className="font-headline">AI Explanation: {title}</DialogTitle>
          <DialogDescription>
            This explanation was generated by AI to help clarify the topic.
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="max-h-[60vh] pr-6">
          <div className="space-y-4 text-sm">
            {isLoading && (
              <div className="flex flex-col items-center justify-center p-8 gap-4">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="text-muted-foreground">Generating explanation...</p>
              </div>
            )}
            {error && (
              <Alert variant="destructive">
                <AlertTriangle className="h-4 w-4" />
                <AlertTitle>Error</AlertTitle>
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}
            {explanation && (
              <div className="prose prose-sm dark:prose-invert max-w-none leading-relaxed">
                {explanation.split('\n').map((paragraph, i) => {
                  if (paragraph.startsWith('* ')) {
                      return <ul key={i} className="my-2"><li>{paragraph.substring(2)}</li></ul>
                  }
                  if (paragraph.trim() === '') return null;
                  return <p key={i}>{paragraph}</p>
                })}
              </div>
            )}
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
